name: Backport merged pull request
on:
  pull_request_target:
    # Run on merge (close) or if label is added after merging
    types: [closed, labeled]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v1
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}
  open-issue:
    name: Open issue for failed backports
    runs-on: ubuntu-latest
    needs: backport
    steps:
      - uses: actions/checkout@v4
        # Open an issue only if the backport job failed
        if: ${{ needs.backport.outputs.was_successful }} == 'false'
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        with:
          filename: .github/templates/failed-backport-issue.md
