name: fedimint-ui-docker

on:
  push:
    paths:
      - package.json
      - yarn.lock
      - .github/workflows/fedimint-ui-docker.yml
      - apps/router/**
      - packages/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            fedimintui/fedimint-ui
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=sha

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: fedimintui
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push fedimint-ui
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout repository content
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4

      # This workflow requires the repository content to be locally available to read the README
      - name: Update the Docker Hub description
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: fedimintui
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: fedimintui/fedimint-ui
          readme-filepath: ./README.md
