name: gateway-ui

on:
  push:
    paths:
      - package.json
      - yarn.lock
      - .github/workflows/gateway-ui.yml
      - apps/gateway-ui/**
      - packages/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            fedimintui/gateway-ui
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          username: fedimintui
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push gateway-ui
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.gateway-ui
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
